nohup python ./main.py \
                --data ./dset/EEG/train_concat_data.npz \
                -b 256 \
                --workers 0 \
                -wd 1e-5 \
                --warmup 0 \
                --gpu-index 3 \
                --device 'cuda' \
                --fp16precision \
                --finetune_epochs 10 \
                --finetune_lr 2e-5 \
                --in_channel 1 \
                --h_dim 256 \
                --vocab_size 10000 \
                --beta 0.5 \
                --dropout 0.1 \
                --n_labels 5 \
                --finetune &>./logs/finetune.log &
